pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["add_a_fso.htm","Add a Faceted Search Orchestrator","Add a Faceted Search Orchestrator Top Previous Next Any use of faceted navigation requires a Faceted Search Orchestrator (FSO) web part. This web ...",""],
["add_the_facet_selectors.htm","Add the Facet Selectors","Add the Facet Selectors Top Previous Next We need three facet selectors for the following associations of different types: 1. Person has skill (hi...",""],
["administrators_guide.htm","Administrators&#39; Guide","Administrators&#39; Guide Top Previous Next This chapter contains information for EPiServer administrators and the facilties provided by them within t...",""],
["allow_httppost_to_web_service.htm","Allow HttpPost to web service","Allow HttpPost to web service Top Previous Next The TMCore EPiServer Module contains an AJAX component that executes in the editors&#39; web browser. ...",""],
["appsettings.htm","AppSettings","AppSettings Top Previous Next The main configuration options for the TMCore EPiServer Module are specified as values in the appSettings section of...",""],
["ar01s01s01.htm","Requirements","Requirements Top Previous Next The TMIS makes use of Windows Communication Foundation (WCF), which is a .NET 3.0 technology, in both the client an...",""],
["ar01s01_1.htm","Components","Components Top Previous Next These are the components to the EPiServer Module: 1. The EPiServer Plug-Ins. There are two plug-ins for the EPiServer...",""],
["ar01s02.htm","Administrator Responsibilities","Administrator Responsibilities Top Previous Next The following sections describe the main administration tasks for the TMCore EPiServer Module. Ma...",""],
["ar01s02s01.htm","Mapping Page Types to Topic Types","Mapping Page Types to Topic Types Top Previous Next An EPiServer administrator is responsible for mapping EPiServer page types to TMCore topic typ...",""],
["ar01s02s01_1.htm","Pre-Loading Schema Topic IDs","Pre-Loading Schema Topic IDs Top Previous Next One aspect of the schema that greatly affects the application initialization time is time spent ret...",""],
["ar01s02s01_2.htm","The Topic Map Editor Tab","The Topic Map Editor Tab Top Previous Next When using legacy edit mode in EPiServer CMS 7 you will notice that there is a new tab available titled...",""],
["ar01s02s01_3.htm","Web.Config","Web.Config Top Previous Next In order to communicate with the TMIS server, WCF clients need to be configured to communicate with the server. This ...",""],
["ar01s02s01_4.htm","Determining the Subject Types","Determining the Subject Types Top Previous Next The types of subject for a site determine how the content of the site will be classified. You can ...",""],
["ar01s02s02.htm","Mapping EPiServer Pages to Topics","Mapping EPiServer Pages to Topics Top Previous Next An EPiServer administrator is also responsible for creating a EPiServer page types to TMCore t...",""],
["ar01s02s02_1.htm","The Topic Map Editor Control","The Topic Map Editor Control Top Previous Next Selecting the Topic Map tab makes available the Topic Map Editor Control. This control is used to c...",""],
["ar01s02s02_2.htm","Event Handlers","Event Handlers Top Previous Next The presence of the networkedplanet.topicmapindex.endpoint in the web.config file also causes event handlers to b...",""],
["ar01s02s02_3.htm","Determining The Content Types","Determining The Content Types Top Previous Next There are two guiding principals for deciding when to create a new content type. Firstly you shoul...",""],
["ar01s02s03.htm","Mapping Page Properties to Occurrences","Mapping Page Properties to Occurrences Top Previous Next The TMCore EPiServer Module also allows the administrator to map page properties to occur...",""],
["ar01s02s03_1.htm","Determining Association Types","Determining Association Types Top Previous Next Now that you have a list of content and subject types, you must determine how individual items of ...",""],
["ar01s02s04.htm","Configuring Administrator Only and Hidden Association Types","Configuring Administrator Only and Hidden Association Types Top Previous Next It is often desirable to hide particular association types from the ...",""],
["ar01s02s04_1.htm","Determine Occurrence Types","Determine Occurrence Types Top Previous Next In Topic Maps, topics can be connected to additional information relating to the topic using occurren...",""],
["ar01s02s05.htm","Restricted Classification Editor Instance Lists","Restricted Classification Editor Instance Lists Top Previous Next When editors select an association slot for editing this causes the TMCore EPiSe...",""],
["ar01s02s05_1.htm","Define Hierarchies","Define Hierarchies Top Previous Next Tree-like structures provide an easily visualised, and well-understood means of organising information. Hiera...",""],
["ar01s02s06.htm","Specifying Pickers in the Classification Editor","Specifying Pickers in the Classification Editor Top Previous Next The following information applies only to the legacy editing mode in CMS 7. The ...",""],
["ar01s02s07.htm","Modifying the list of associations shown in the classification editor","Modifying the list of associations shown in the classification editor Top Previous Next The TMCore EPiServer Module creates as list of association...",""],
["ar01s02_2.htm","The Role of the Topic Map Schema","The Role of the Topic Map Schema Top Previous Next An NPCL topic map schema can be defined using the TMCore topic map editor and allows developers...",""],
["ar01s02_3.htm","Legacy Editing Interface","Legacy Editing Interface Top Previous Next The Topic Map Editor Control is the main legacy editor control provided as part of the topic map module...",""],
["ar01s02_4.htm","Installation &#38; Configuration","Installation &#38; Configuration Top Previous Next To install the integration, copy the contents of the bin folder in to your EPiServer&#39;s web applicat...",""],
["ar01s02_5.htm","Pre-requisites","Pre-requisites Top Previous Next Before beginning the installation of the TMCore EPiServer Module components ensure that the following components ...",""],
["ar01s02_6.htm","Types Analysis Phase","Types Analysis Phase Top Previous Next The first stage is to analyse the content you want to present on a site. The purpose of this analysis is to...",""],
["ar01s03.htm","Admin Tools","Admin Tools Top Previous Next The TMCore EPiServer Module Admin plug-in is a convenient utility to allow administrators to configure the TMCore EP...",""],
["ar01s03s01.htm","Configuration Checker","Configuration Checker Top Previous Next The configuration checker performs a rudimentary check on the configuration options to ensure that they ar...",""],
["ar01s03s01_2.htm","Topic Clouds","Topic Clouds Top Previous Next Topic Clouds are extensions of Tag Clouds , commonly used on the web as an efficient way of showing a set of availa...",""],
["ar01s03s01_4.htm","Connect to the TMEditor Application","Connect to the TMEditor Application Top Previous Next TMEditor is a web application which is distributed as part of the TMCore distribution. You o...",""],
["ar01s03s02.htm","Topic Map Consistency Checker","Topic Map Consistency Checker Top Previous Next The Topic Map Consistency Checker is a utility that ensures that the topic map, managed by TMCore ...",""],
["ar01s03s02_2.htm","Faceted Navigation &#38; Search","Faceted Navigation &#38; Search Top Previous Next Faceted navigation and search are very powerful navigation methods for web sites. Faceted search is ...",""],
["ar01s03s02_3.htm","Create Subject and Content Type Topics","Create Subject and Content Type Topics Top Previous Next For each content and subject type you must create a new topic. This can be achieved by en...",""],
["ar01s03s03.htm","Migrating data from a development environment to a deployment environment","Migrating data from a development environment to a deployment environment Top Previous Next Development of EPiServer solutions often occur on a de...",""],
["ar01s03s03_1.htm","Create Association Types","Create Association Types Top Previous Next For each association you identified between two topic types, you will need to create three topics and s...",""],
["ar01s03s04.htm","Redundant Topic Removal","Redundant Topic Removal Top Previous Next If the topic map service misses any page update events - because it has been disabled for example, the t...",""],
["ar01s03s04_1.htm","Create Occurrence Types","Create Occurrence Types Top Previous Next You will need to create one topic for each occurrence type that you identified during the analysis phase...",""],
["ar01s03s05.htm","Create Hierarchies","Create Hierarchies Top Previous This final step is the most complex step in the process. When you create a hierarchy you must specify the followin...",""],
["ar01s03_2.htm","Getting and Displaying Topic Map data in EPiServer Pages","Getting and Displaying Topic Map data in EPiServer Pages Top Previous Next This section goes through the basic steps that are required to get Topi...",""],
["ar01s03_3.htm","Enterprise Web Parts &#38; Controls","Enterprise Web Parts &#38; Controls Top Previous Next This section describes the behaviour and configuration of the web parts that are supplied with t...",""],
["ar01s03_4.htm","Unpacking the Installation Package","Unpacking the Installation Package Top Previous Next The TMCore EPiServer Module is distributed as a zip archive. To install the TMCore EPiServer ...",""],
["ar01s03_5.htm","Ontology Implementation","Ontology Implementation Top Previous Next This section will take you through the process of entering your ontology information into a topic map us...",""],
["ar01s04.htm","Mapping data from EPiServer to the Topic Map","Mapping data from EPiServer to the Topic Map Top Previous Next The TMCore EPiServer Module uses Topic Maps to persist all the data it captures fro...",""],
["ar01s04s01_1.htm","TopicCreating &#38; TopicCreated","TopicCreating &#38; TopicCreated Top Previous Next The TopicCreating and TopicCreated events are fired just before and after a topic is created that r...",""],
["ar01s04s01_2.htm","Association Template Keys XML","Association Template Keys XML Top Previous Next The association template keys format is used to define the types of templates that should be trave...",""],
["ar01s04s01_3.htm","Install files in to the EPiServer instance web application","Install files in to the EPiServer instance web application Top Previous Next Copy the contents of the /webapp directory to the EPiServer web appli...",""],
["ar01s04s02_1.htm","TopicDeleting","TopicDeleting Top Previous Next TopicDeleting events are fired just before a topic is deleted from the topic map. There is no post-delete event. T...",""],
["ar01s04s02_2.htm","Value Select Terms XML","Value Select Terms XML Top Previous Next Value select terms are used on to specify what columns should appear in the dataset returned by TMIS quer...",""],
["ar01s04s02_3.htm","Add configuration information to EPiServer web.config","Add configuration information to EPiServer web.config Top Previous Next The TMCore EPiServer Module reads configuration information from the EPiSe...",""],
["ar01s04s03_1.htm","AssociationDeleting &#38; AssociationPublishing events","AssociationDeleting &#38; AssociationPublishing events Top Previous Next AssociationDeleting and AssociationPublishing events are fired just before an...",""],
["ar01s04s03_2.htm","Run the EPiServer Module SQL script","Run the EPiServer Module SQL script Top Previous Next The TMCore EPiServer Module requires new stored procedures to be added to the database. Usin...",""],
["ar01s04s04_1.htm","Add query handlers to TMCore TMService web.config","Add query handlers to TMCore TMService web.config Top Previous Next The EPiServer Module makes use of the TMCore TMService web service to access T...",""],
["ar01s04s05_1.htm","Select a topic map for use","Select a topic map for use Top Previous Next The TMCore EPiServer Module requires a topic map. By default it expects this topic map to be called &#8220;...",""],
["ar01s04s06.htm","Ensure the EPiServer application pool can access the TMCore database","Ensure the EPiServer application pool can access the TMCore database Top Previous Next All connections through to the TMCore database will be perf...",""],
["ar01s04s07.htm","Install logging configuration file (optional)","Install logging configuration file (optional) Top Previous Next EPiServer uses log4net for providing diagnostic log and trace information for admi...",""],
["ar01s04s08.htm","Internationalization and Customization of Edit Mode Plug-Ins (optional)","Internationalization and Customization of Edit Mode Plug-Ins (optional) Top Previous Next EPiServer allows the internationalization of the names a...",""],
["ar01s04_1.htm","EPiServer Module Events","EPiServer Module Events Top Previous Next The TMCore EPiServer Module allows developers to bind event handlers to particular events so that they m...",""],
["ar01s04_2.htm","XML Schema Reference","XML Schema Reference Top Previous Next Some of the properties exposed by web parts take their value as XML string values. This section contains a ...",""],
["ar01s04_3.htm","Installation and Configuration of TMCore EPiServer Module","Installation and Configuration of TMCore EPiServer Module Top Previous Next This section describes the full installation and configuration of the ...",""],
["ar01s05.htm","Troubleshooting","Troubleshooting Top Previous Next This section outlines common errors in configuration found when installing or using the TMCore EPiServer Module. ",""],
["ar01s05s01.htm","Unable to access Topic Map tab when using a remote server","Unable to access Topic Map tab when using a remote server Top Previous Next Symptoms The Topic Map tab fails to load correctly and in the client t...",""],
["ar01s05s02.htm","Topic Map tab pops up a dialog containing a 404 Not Found Error","Topic Map tab pops up a dialog containing a 404 Not Found Error Top Previous Next Symptom The AJAX classification editor on the topic map tab uses...",""],
["ar01s05s04.htm","Basic Challenge/Response issued when accessing the Topic Map tab","Basic Challenge/Response issued when accessing the Topic Map tab Top Previous Next Symptom When accessing the Topic Map tab the editor is challeng...",""],
["association_deleted_scope.htm","Association Deleted Scope","Association Deleted Scope Top Previous Next When an editor deletes an association from within the Edit Mode Topic Map tab the association is not d...",""],
["association_unpublished_scope.htm","Association Unpublished Scope","Association Unpublished Scope Top Previous Next When an editor creates an association from within the EdIt Mode Topic Map tab the association is c...",""],
["auto_cloud_control.htm","Auto Cloud Control","Auto Cloud Control Top Previous Next The \"Auto Cloud\" control is a special control that uses the topic map ontology to place a set of Topic Clouds...",""],
["cms_7_editing_interface.htm","CMS 7 Editing Interface","CMS 7 Editing Interface Top Previous Next Starting with release 7.0 of the TMCore EPiServer Module, the recommended way to edit the relationships ...",""],
["common_configuration_propertie.htm","Common Configuration Properties","Common Configuration Properties Top Previous Next The following properties are common to all Topic Cloud Web Parts: Property Name Required? Defaul...",""],
["configuring_hidden_association.htm","Configuring Hidden Association Types","Configuring Hidden Association Types Top Previous Next In many situations it is not practical to display to the editor all of the roles that are p...",""],
["creating_new_queries.htm","Creating New Queries","Creating New Queries Top Previous Next If required, the developer can construct new queries for use with the ASP.NET controls that can understand ...",""],
["customizing_the_generated_xml.htm","Customizing the Generated XML","Customizing the Generated XML Top Previous Next The XML generated by Topic Cloud controls is derived from a System.Data.DataSet using the GetXml m...",""],
["designguide.htm","TMCore EPiServer Module Design","TMCore EPiServer Module Design Top Previous Next This chapter describes the different components of the TMCore EPiServer Module and how they inter...",""],
["developers_guide.htm","Developers&#39; Guide","Developers&#39; Guide Top Previous Next This document contains information for administrators and developers of EPiServer page types and templates on ...",""],
["document_conventions.htm","Document Conventions","Document Conventions Top Previous Next In this documentation we make use of a number of different type-faces and colours to convey different infor...",""],
["editing_related_topics.htm","Editing Related Topics","Editing Related Topics Top Previous Next To add a new topic to a related topics list: 1. Click on the related topics list you wish to add. This li...",""],
["editorguide.htm","Editors&#39; Guide","Editors&#39; Guide Top Previous Next This chapter describes how EPiServer editors use the TMCore EPiServer Module as part of the content authoring pro...",""],
["enable_the_topic_map_gadget.htm","Enable the Topic Map Gadget","Enable the Topic Map Gadget Top Previous Next To add support for topic editing to your CMS 7 editing interface you simply need to add the Topic Ma...",""],
["faceted_navigation.htm","Faceted Navigation","Faceted Navigation Top Previous Next Faceted navigation allows the user to narrow down a large information set down to the precise information tha...",""],
["faceted_search.htm","Faceted Search","Faceted Search Top Previous Next Faceted search is similar to faceted navigation, the only difference is that initial set of topics shown in the r...",""],
["getrelateddatabyonehop.htm","GetRelatedDataByOneHop","GetRelatedDataByOneHop Top Previous Next This method returns a DataSet instance containing the topic ID of the page topics found, EPiServer page I...",""],
["getrelateddatabytwohop.htm","GetRelatedDataByTwoHop","GetRelatedDataByTwoHop Top Previous Next This method exposes a DataSet instead of a PageDataCollection. This method can return a DataSet in two fo...",""],
["getrelatedpagesbyonehop.htm","GetRelatedPagesByOneHop","GetRelatedPagesByOneHop Top Previous Next This method returns a PageDataCollection of all the pages that were found during the query. This is the ...",""],
["getrelatedpagesbytwohop.htm","GetRelatedPagesByTwoHop","GetRelatedPagesByTwoHop Top Previous Next This method is used to find pages which are indirectly connected to this page via another page. For exam...",""],
["hiding_association_types_based.htm","Hiding Association Types Based On Security Role","Hiding Association Types Based On Security Role Top Previous Next There may be security implications with allowing all editors to see all the role...",""],
["hierarchy_picker.htm","Hierarchy Picker","Hierarchy Picker Top Previous Next The hierarchy picker tab shows any available hierarchies for the association. A list of available hierarchies i...",""],
["id_picker.htm","ID Picker","ID Picker Top Previous Next The ID picker tab allows the editor to quickly find a topic by its Page ID. Enter the Page ID of the page to view its ...",""],
["index_server_integration.htm","Topic Map Index Server Integration","Topic Map Index Server Integration Top Previous Next The Topic Map Index Server (TMIS) by Networked Planet provides a standalone index service for...",""],
["installation_guide.htm","Installation Guide","Installation Guide Top Previous Next This document describes how to install and configure the TMCore EPiServer Module. It is recommended to read t...",""],
["install_the_topic_map_addon.htm","Install The Topic Map AddOn","Install The Topic Map AddOn Top Previous Next The Topic Map AddOn provides a topic editing interface integrated into the new EPiServer CMS7 editin...",""],
["introduction.htm","Introduction","Introduction Top Next The TMCore EPiServer Module is a suite of components that allows developers to add the power of the Topic Maps standard to t...",""],
["mapping_topic_associations.htm","Topic Associations","Topic Associations Top Previous Next Each association created in the Edit mode Topic Map component (or Topic Map tab in the legacy editing UI) is ...",""],
["mapping_topic_name_information.htm","Topic Name Information","Topic Name Information Top Previous Next EPiServer has powerful internationalization and globalization support as standard. Each page may have sev...",""],
["mapping_topic_occurrence_information.htm","Topic Occurrence Information","Topic Occurrence Information Top Previous Next Each page topic contains two occurrences: 1. The ID of the page in EPiServer. 2. A URL of the page ...",""],
["mapping_topic_schema_information.htm","Topic Schema Information","Topic Schema Information Top Previous Next The NPCL schema, defined within the topic map, is used to drive the presentation of the editor&#39;s user i...",""],
["mapping_topic_subject_identifier.htm","Topic Subject Identifier (URN GUID)","Topic Subject Identifier (URN GUID) Top Previous Next The page topic subject identifier is critical to the operation of the EPiServer Module as it...",""],
["np_tm_aspnet_client_base.htm","NP_TM_ASPNET_CLIENT_Base","NP_TM_ASPNET_CLIENT_Base Top Previous Next This should be set to the path, on the local web server to where the aspnet_client files are installed....",""],
["np_tm_defaultpickerlist.htm","NP_TM_DefaultPickerList","NP_TM_DefaultPickerList Top Previous Next This allows administrators to define a default set of pickers that will be shown to the editor when clas...",""],
["np_tm_enableclienttrace.htm","NP_TM_EnableClientTrace","NP_TM_EnableClientTrace Top Previous Next When set to true this enables client-side trace to be generated by the EPiServer Module AJAX controls. D...",""],
["np_tm_languagecodeprefix.htm","NP_TM_LanguageCodePrefix","NP_TM_LanguageCodePrefix Top Previous Next This is the prefix applied to the subject identifier of each topic that is used to scope a topic name f...",""],
["np_tm_npcl_endpoint.htm","NP_TM_NPCL_Endpoint","NP_TM_NPCL_Endpoint Top Previous Next This is the URL of the TMCore NPCL web service endpoint that will be used by the EPiServer module. The defau...",""],
["np_tm_pageidoccurrencetypepsi.htm","NP_TM_PageIdOccurrenceTypePsi","NP_TM_PageIdOccurrenceTypePsi Top Previous Next This is the subject identifier of the topic that will be used to type occurrences attached to topi...",""],
["np_tm_pagelinkoccurrencetypeps.htm","NP_TM_PageLinkOccurrenceTypePsi","NP_TM_PageLinkOccurrenceTypePsi Top Previous Next This is the public subject identifier (PSI) of the topic that will be used to type occurrences a...",""],
["np_tm_showtypeonexistingassoci.htm","NP_TM_ShowTypeOnExistingAssociations","NP_TM_ShowTypeOnExistingAssociations Top Previous Next The value of this property determines whether the page type and/or topic type names should ...",""],
["np_tm_showtypeonsearchpicker.htm","NP_TM_ShowTypeOnSearchPicker","NP_TM_ShowTypeOnSearchPicker Top Previous Next This property determines whether the page type and/or topic type names should be shown in the table...",""],
["np_tm_tmws_endpoint.htm","NP_TM_TMWS_Endpoint","NP_TM_TMWS_Endpoint Top Previous Next This is the URL of the TMCore TMService endpoint that will be used by the EPiServer module. The default valu...",""],
["np_tm_topicmapname.htm","NP_TM_TopicMapName","NP_TM_TopicMapName Top Previous Next This is the name of the topic map what will be used to access and persist topic information. Default value: E...",""],
["np_tm_topicpsi.htm","NP_TM_TopicPsi","NP_TM_TopicPsi Top Previous Next This is the name of the page property that will used for pages that should be merged with an existing topic. This...",""],
["np_tm_topicsipageproperty.htm","NP_TM_TopicSIPageProperty","NP_TM_TopicSIPageProperty Top Previous Next This is the name of an EPiServer Page Property that will store an automatically generated topic identi...",""],
["np_tm_topictype.htm","NP_TM_TopicType","NP_TM_TopicType Top Previous Next The value of this configuration attribute is the name of the page property that must be defined on topic-aware p...",""],
["onehop_and_twohop.htm","OneHop and TwoHop Queries","OneHop and TwoHop Queries Top Previous Next The one and two hop helpers are used to provide navigation links from the page currently being viewed ...",""],
["one_hop_queries.htm","One Hop Queries","One Hop Queries Top Previous Next A OneHop query is a query that finds all the pages that are connected by a single association (or hop) to the pa...",""],
["ontologycreationguide.htm","Ontology Development Guide","Ontology Development Guide Top Previous Next The TMCore EPiServer Module provides a simple, but extremely powerful approach to organising and pres...",""],
["page_id_occurrence.htm","Page ID Occurrence","Page ID Occurrence Top Previous Next An occurrence is created on each page topic containing resource data which is the integer ID of the page as t...",""],
["page_link_occurrence.htm","Page Link Occurrence","Page Link Occurrence Top Previous Next An occurrence is created on each page topic containing a resource link which is the relative URL for the pa...",""],
["prepare_tmcore.htm","Prepare TMCore","Prepare TMCore Top Previous Next The following steps need to be performed just once on your TMCore server. These steps create some new stored proc...",""],
["reading_this_documentation.htm","Reading This Documentation","Reading This Documentation Top Previous Next The documentation is split up into several different sections each targeted to a specific kind of use...",""],
["saving_and_publishing_changes.htm","Saving and Publishing Changes","Saving and Publishing Changes Top Previous Next Any changes you make to a topic in the Topic Map gadget are not stored on the server until you pre...",""],
["showing_the_results.htm","Showing the Results","Showing the Results Top Previous Next The results of faceted navigation and search queries are often shown in a way specific to a solution. Also t...",""],
["styling_cloud_controls.htm","Styling Cloud Controls","Styling Cloud Controls Top Previous Next Topic clouds can be styled via very simple XSL. The simplest styling, used in the screenshots for this do...",""],
["topic_list_picker.htm","Topic List Picker","Topic List Picker Top Previous Next The topic list picker allows the editor to see a list of all the potentially associated topics and refine by a...",""],
["topic_of_type_cloud.htm","Topic of Type Cloud","Topic of Type Cloud Top Previous Next The Topic of Type Cloud for EPiServer is available in the NetworkedPlanet.EPiServerTopicMapIndexModule.WebPa...",""],
["two_hop_queries.htm","Two Hop Queries","Two Hop Queries Top Previous Next A Two Hop Query is used to find all pages that are indirectly connected to a starting page via some other page. ...",""],
["upgrading_from_6_x.htm","Upgrading from 6.x","Upgrading from 6.x Top Previous Next This section assumes that you are upgrading a site that was built using version 6.x of the TMCore EPiServer M...",""],
["using_episerver_typed_models.htm","Using EPiServer Typed Models","Using EPiServer Typed Models Top Previous Next As described in the sections Mapping Page Types to Topic Types and Mapping EPiServer Pages to Topic...",""],
["using_the_hierarchy_picker.htm","Using The Hierarchy Picker","Using The Hierarchy Picker Top Previous Next The Hierarchy Picker can be used to select a related topic by browsing through one of the hierarchies...",""],
["using_the_page_id_search_picke.htm","Using the Page ID Search Picker","Using the Page ID Search Picker Top Previous Next The Page ID Search Picker allows you to make a relationship to another page in EPiServer by ente...",""],
["using_the_topic_map_gadget.htm","Using The Topic Map Gadget","Using The Topic Map Gadget Top Previous Next The screenshot below shows the Topic Map gadget and its different components. The Topic Map Gadget di...",""],
["using_the_topic_search_picker.htm","Using The Topic Search Picker","Using The Topic Search Picker Top Previous Next The Topic Search Picker can be used to find a related topic using a search on the topic name. The ...",""],
["walkthrough_creating_a_custom_.htm","Walkthrough: Creating a Custom Query","Walkthrough: Creating a Custom Query Top Previous Next This example demonstrated how to create a new query and include the results from within a p...",""]];
