pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["actionrepr.htm","ActionRepr","ActionRepr Top Previous Next Description Representation of a single operation within a Transaction. XML Representation %resource uri% %etag% %requ...",""],
["add.htm","add","add Top Previous Next Each add element provides the connection string for one of the databases. Each element has the following attributes: Attribu...",""],
["adding_arcs.htm","Adding Arcs","Adding Arcs Top Previous Next To create a new Arc type, simply drag the Arc Type shape from the toolbox onto the canvas and enter the name and ide...",""],
["adding_binary_associations.htm","Adding Binary Associations","Adding Binary Associations Top Previous Next As well as defining topic types the other main schema construct are association templates. An associa...",""],
["adding_complex_associations.htm","Adding Complex Associations","Adding Complex Associations Top Previous Next The simplest way to create a complex association is to create the Association Type and then connect ...",""],
["adding_occurrence_types_and_co.htm","Adding Topic Properties and Constraints","Adding Topic Properties and Constraints Top Previous Next Occurrence types and constraints define the properties allowed on instances of a given t...",""],
["add_new_topic_types.htm","Adding New Topic Types","Adding New Topic Types Top Previous Next To add a new topic type simply drag the topic type tool from the palette on the left onto the main canvas...",""],
["add_schema.htm","Add-Schema","Add-Schema Top Summary Add-Schema [-Web3Address] [-FilePath] Description Creates a new schema in the specified service using the XML representatio...",""],
["administration.htm","Administration","Administration Top Previous Next ",""],
["adroleprovider.htm","adRoleProvider","adRoleProvider Top Previous Next This element wraps the configuration information required to use the Active Directory Role Provider. This section...",""],
["anonymous_user.htm","Anonymous User","Anonymous User Top Previous Next The Anonymous user is a default user account that is added to the Web3 Platform security database on installation...",""],
["api_class_overview.htm","API Class Overview","API Class Overview Top Previous Next There are two client classes that act as starting points for accessing the Web3 services, the TopicMapService...",""],
["arc.htm","Arc","Arc Top Previous Next Path /topicmaps/{tm}/arcs/{arc} Description A single arc in the topic map Supported HTTP Operations HTTP Method Description ...",""],
["arcrepr.htm","ArcRepr","ArcRepr Top Previous Next Description Represents a single arc in a topic map XML Representation See TopicRef See TopicRef See TopicRef See Identif...",""],
["arcs.htm","Arcs","Arcs Top Previous Next Arcs are a Web3 extension to the Topic Map data model that allow for simpler topic-to-topic relationships than associations...",""],
["arcs_collection.htm","Arcs Collection","Arcs Collection Top Previous Next Path /topicmaps/{tm}/arcs Description The collection of arcs in a topic map Supported HTTP Operations HTTP Metho...",""],
["arcs_list_page.htm","Arcs List Page","Arcs List Page Top Previous Next The Arcs List Page shows a list of all topics that are connected to a particular starting topic using a particula...",""],
["arc_editors.htm","Arc Editors","Arc Editors Top Previous Next Arc Editors appear and behave in exactly the same way as Binary Association Editors. Arc editors are displayed for e...",""],
["association.htm","Association","Association Top Previous Next Path /topicmaps/{tm}/associations/{association} Description A single association in the topic map Supported HTTP Ope...",""],
["associationrepr.htm","AssociationRepr","AssociationRepr Top Previous Next Description Represents a single association in a topic map XML Representation See TopicRef See TopicRef * See Ro...",""],
["associations.htm","Associations","Associations Top Previous Next Associations are the general form for the representation of relationships between topics in a topic map. An associa...",""],
["authentication.htm","Authentication","Authentication Top Previous Next The Web3 Platform uses Windows Authentication in its REST interfaces to determine the identity of the user. The d...",""],
["authentication_and_authorizati.htm","Authentication and Authorization","Authentication and Authorization Top Previous Next The Web3 client APIs support user authentication via either HTTP user credentials or OAuth 1.0 ...",""],
["authorization.htm","Authorization","Authorization Top Previous Next Authorization is a process that determines if a user has a particular privilege on a Store or Partition. A user ma...",""],
["binary_associations_list_page.htm","Binary Associations List Page","Binary Associations List Page Top Previous Next The Binary Association List Page shows all topics that play a particular type of role in a particu...",""],
["binary_association_editors.htm","Binary Association Editors","Binary Association Editors Top Previous Next Binary Association Editors are displayed for all association templates that involve only two topics. ...",""],
["cache.htm","cache","cache Top Previous Next This element allows the configuration of the default cache period used by the server. The element has a single attribute n...",""],
["cache_control_and_etags.htm","Cache Control and ETags","Cache Control and ETags Top Previous Next A GET request on a resource will typically return a set of cache control headers. These include: ETag: a...",""],
["caching_in_the_web3_platform.htm","Caching in the Web3 Platform","Caching in the Web3 Platform Top Previous Next There are several other concepts around the APIs that are important to understand when developing a...",""],
["chapter_2.htm","Overview of the Web3 Platform APIs","Overview of the Web3 Platform APIs Top Previous Next This section provides an overview of the different Web3 Platform APIs. ",""],
["clientapps.htm","clientApps","clientApps Top Previous Next This is the wrapper element for configuration options that are specific to the client applications included in the We...",""],
["clientlanguages.htm","clientLanguages","clientLanguages Top Previous Next The content of this element lists the possible languages that client applications should allow users to choose b...",""],
["command_reference.htm","Command Reference","Command Reference Top Previous Next This section provides the detailed command-line reference for each of the cmdlets added by the Web3Admin Power...",""],
["commithandler.htm","commitHandler","commitHandler Top Previous Next This element contains a reference a class that is notified of commits that occur on the Web3 front-end server. The...",""],
["commitqueue.htm","commitQueue","commitQueue Top Previous Next This element specifies the name of a message queue that Web3 Platform commit messages should be written to. Multiple...",""],
["commitqueues.htm","commitQueues","commitQueues Top Previous Next This is a wrapper element for a list of MSMQ queues to post messages to when updates are made to the topic map stor...",""],
["common_rest_api_features.htm","Common REST API Features","Common REST API Features Top Previous Next ",""],
["complete_server_installation.htm","Complete Server Installation","Complete Server Installation Top Previous Next The Complete Server installation process allows you to install all of the Web3 Platform services an...",""],
["complex_associations_list_page.htm","Complex Associations List Page","Complex Associations List Page Top Previous Next The Complex Associations List Page shows all associations where the current topic (whose name is ...",""],
["complex_association_editors.htm","Complex Association Editors","Complex Association Editors Top Previous Next When the topic map schema defines an association template with more than two roles to it, the topic ...",""],
["components_of_a_web3_installat.htm","Components of a Web3 Installation","Components of a Web3 Installation Top Previous Next The diagram below shows the different components of a Web3 installation and their logical grou...",""],
["concepts.htm","Concepts","Concepts Top Previous Next This section introduces the key concepts and standards behind the Web3 Platform. ",""],
["configuration.htm","configuration","configuration Top Previous Next This is the root element of the connectionStrings.xml configuration file. It contains a single connectionStrings c...",""],
["connectionstrings.htm","connectionStrings","connectionStrings Top Previous Next This is the wrapper element for the list of database connection strings used by the Web3 services. Each databa...",""],
["connectionstrings_xml.htm","connectionStrings.xml","connectionStrings.xml Top Previous Next This file contains a list of all of the connection strings used by the Web3 Platform services to connect t...",""],
["constraintpropertyrepr.htm","ConstraintPropertyRepr","ConstraintPropertyRepr Top Previous Next Description Represents a single extension property name/value pair attached to a constraint. XML Represen...",""],
["constraintrepr2.htm","ConstraintRepr","ConstraintRepr Top Previous Next Description Represents a single constraint in a schema. XML Representation %si% %si% %si% %si% %si% %si% %si% %si...",""],
["constraints.htm","Constraints","Constraints Top Previous Next Constraints define limits on the topic map based on the schema types. There are two basic categories of constraint: ...",""],
["constrainttypeidentifiers.htm","Constraint Type Identifiers","Constraint Type Identifiers Top Previous Next The following table lists all of the supported TMCL constraint identifiers. To save space, the table...",""],
["conventions_used_in_this_refer.htm","Conventions Used In This Reference","Conventions Used In This Reference Top Previous Next The following conventions are used in this reference documentation for clarity and compactnes...",""],
["creating_a_new_hierarchy.htm","Creating A New Hierarchy","Creating A New Hierarchy Top Previous Next The creation of a new hierarchy in a topic map requires several pieces of information. 1. The hierarchy...",""],
["creating_a_new_schema.htm","Creating A New Schema","Creating A New Schema Top Previous Next To create a new schema click the &#39;New Schema&#39; button and the following dialog will appear. Create Schema D...",""],
["creating_a_new_topic_map.htm","Creating A New Topic Map","Creating A New Topic Map Top Previous Next To create a new topic map click on &#39;Create New Topic Map&#39;. This will bring up the following dialog. Cre...",""],
["creating_a_schema.htm","Creating a Schema","Creating a Schema Top Previous Next The first activity in any Web3 development is to create a schema. Calling CreateSchema on the SchemaServiceCli...",""],
["creating_a_topic_map.htm","Creating a Topic Map","Creating a Topic Map Top Previous Next To create a topic map, first create a TopicMapServiceClient instance, then use the CreateTopicMap() method ...",""],
["database_server_installation.htm","Database Server Installation","Database Server Installation Top Previous Next The Database Server installation can be used to simply create the Web3 databases without installing...",""],
["date_time_editor.htm","Date/Time Editor","Date/Time Editor Top Previous Next A Date/Time Editor is similar to a Validating Text Editor as it displays a text box and validates the input, di...",""],
["defining_a_hierarchy.htm","Defining a Hierarchy","Defining a Hierarchy Top Previous Next Hierarchies are views onto topic maps. They define a root node and also define which association types shou...",""],
["defining_schema_constants.htm","Defining Schema Constants","Defining Schema Constants Top Previous Next This is not a required step, but it is considered best practice. When working with topic maps and sche...",""],
["deleting_a_hierarchy_definitio.htm","Deleting A Hierarchy Definition","Deleting A Hierarchy Definition Top Previous Next Deleting a hierarchy can be quickly and easily performed by deleting the Hierarchy Definition. T...",""],
["deployment_configurations.htm","Deployment Configurations","Deployment Configurations Top Previous Next Before you start installing the Web3 Platform - especially if you plan a large, multi-machine installa...",""],
["developers_edition_installatio.htm","Developers&#39; Edition Installation","Developers&#39; Edition Installation Top Previous Next The Web3 Developers&#39; Edition is a complete, standalone version of the Web3 platform for use in ...",""],
["developers_guide.htm","Developers&#39; Guide","Developers&#39; Guide Top Previous Next The developers&#39; guide provides information about the Web3 Platform product architecture, the APIs and examples...",""],
["developing_with_the__net_clien.htm","Developing with the .NET Client","Developing with the .NET Client Top Previous Next Introduction The Web3 platform comprises a set of RESTful services that allow client application...",""],
["editing_a_hierarchy_definition.htm","Editing A Hierarchy Definition","Editing A Hierarchy Definition Top Previous Next If you want to change which associations are used to build a hierarchy or to modify the list of r...",""],
["editing_hierarchy_content.htm","Editing Hierarchy Content","Editing Hierarchy Content Top Previous Next The content of a hierarchy can be edited simply by creating new associations of the appropriate type, ...",""],
["enabling_large_uploads.htm","Enabling Large Uploads","Enabling Large Uploads Top Previous Next When XTM or RDF data is imported into a Web3 instance, the data to be imported must be transferred to Web...",""],
["error_handling.htm","Error Handling","Error Handling Top Previous Next The client API wraps all HTTP errors that it may receive from the service. It turns these errors into client exce...",""],
["error_status_codes.htm","Error Status Codes","Error Status Codes Top Previous Next The Web3 server uses standard HTTP status codes where possible: 404 Not Found - returned when attempting to a...",""],
["eventhandler.htm","eventHandler","eventHandler Top Previous Next The eventHandler element allows the configuration of external custom event handlers that are invoked when updates a...",""],
["eventthreshold.htm","eventThreshold","eventThreshold Top Previous Next This element specifies the level of logging for messages written to the system Event Log. Event log messages can ...",""],
["example_queries.htm","Example Queries","Example Queries Top Previous Next Filtering by Numeric Value PREFIX c: PREFIX tms: SELECT ?exchange ?lbl WHERE { ?exchange a c:exchange . ?exchang...",""],
["expanding_topics_in_sparql_que.htm","Expanding Topics in SPARQL Query Results","Expanding Topics in SPARQL Query Results Top Previous Next In some cases it is desirable to retrieve more than just the URI address of a topic - f...",""],
["export_topicmap.htm","Export-TopicMap","Export-TopicMap Top Previous Next Summary Export-TopicMap [-TopicMapAddress] [[-FilePath] ] [-ForceOverwrite] Description Exports topic map data a...",""],
["extension_properties_editor.htm","Extension Properties Editor","Extension Properties Editor Top Previous Next The Extension Properties Editor allows you to add your own meta data properties to types and constra...",""],
["filethreshold.htm","fileThreshold","fileThreshold Top Previous Next This element specifies the level of logging for messages written to the log file in the Web3 Hive Directory . The ...",""],
["finding_instances_of_a_type.htm","Finding Instances of a Type","Finding Instances of a Type Top Previous Next SPARQL uses the special RDF predicate URL xxx to find the type of an item. Our implementation uses t...",""],
["finding_or_filtering_on_topic_.htm","Finding or Filtering on Topic Properties","Finding or Filtering on Topic Properties Top Previous Next Retrieving Topic Property Values Topic properties can be retrieved referring to the top...",""],
["front_end_server_installation.htm","Front-End Server Installation","Front-End Server Installation Top Previous Next The Front-End Server installation process is used to install the Web3 windows services and Web3 we...",""],
["fulltopicrepr.htm","FullTopicRepr","FullTopicRepr Top Previous Next Description Represents a complete set of all information relating to a single topic - all of its properties, ident...",""],
["full_text_search.htm","Full-Text Search","Full-Text Search Top Previous Next Full-text search against topic labels and property values is supported through an extension predicate . This pr...",""],
["getting_topic_labels.htm","Getting Topic Labels","Getting Topic Labels Top Previous Next To Retrieve all Labels for a Topic The special predicate http://www.networkedplanet.com/tmsparql/label can ...",""],
["get_schema.htm","Export-Schema","Export-Schema Top Previous Next Summary Export-Schema [-SchemaAddress] [-FilePath] [-ForceOverwrite] Description Retrieves and writes to disk the ...",""],
["get_topicmapjobs.htm","Get-TopicMapJobs","Get-TopicMapJobs Top Previous Next Summary Get-TopicMapJobs [-TopicMapAddress] Description Returns a list of the most recent 20 long-running topic...",""],
["granting_and_revoking_permissi.htm","Granting and Revoking Permissions","Granting and Revoking Permissions Top Previous Next Please refer to the documentation for the Grant-StorePermission and Grant-TopicMapPermission p...",""],
["granting_database_access.htm","Granting Database Access","Granting Database Access Top Previous Next Every domain user account that is used to run the Web3 windows services or Web3 application pool will r...",""],
["granting_unauthenticated_acces.htm","Granting Unauthenticated Access","Granting Unauthenticated Access Top Previous Next To configure a Web3 instance for unauthenticated access, it is necessary to modify the WCF servi...",""],
["grant_schemapermission.htm","Grant-SchemaPermission","Grant-SchemaPermission Top Previous Next Summary Grant-SchemaPermission [-SchemaAddress] [-Permissions] [-Principals] Description Allows permissio...",""],
["grant_storepermission.htm","Grant-StorePermission","Grant-StorePermission Top Previous Next Summary Grant-StorePermission [-StoreUri] [-Permissions] [-Principals] Description Assigns permissions to ...",""],
["grant_topicmappermission.htm","Grant-TopicMapPermission","Grant-TopicMapPermission Top Previous Next Summary Grant-TopicMapPermission [-TopicMapAddress] [-Permissions] [-Principals] Description Allows per...",""],
["hardware_requirements.htm","Hardware Requirements","Hardware Requirements Top Previous Next The hardware requirements for Web3 depend on the role(s) played by the machine in the deployment. We ident...",""],
["hierarchies.htm","Hierarchies","Hierarchies Top Previous Next The topic map editor allows you to create and modify hierarchy definitions and to directly edit the parents and chil...",""],
["hierarchydefrepr.htm","HierarchyDefRepr","HierarchyDefRepr Top Previous Next Description XML Representation The topic that represents the hierarchy. See TopicRef see TopicRef * See TopicRe...",""],
["hierarchyitemrepr.htm","HierarchyItemRepr","HierarchyItemRepr Top Previous Next Description Represents a link between a parent and a child in a hierarchy XML Representation See TopicRef See ...",""],
["hierarchynoderepr.htm","HierarchyNodeRepr","HierarchyNodeRepr Top Previous Next Description XML Representation see TopicRef see HiearchyItemRepr * see HierarchyItemRepr * JSON Representation...",""],
["hierarchy_definition.htm","Hierarchy Definition","Hierarchy Definition Top Previous Next Path /topicmaps/{tm}/hierarchies/{hierarchyId} Description A hierarchy definition contained in a topic map....",""],
["hierarchy_list.htm","Hierarchy List","Hierarchy List Top Previous Next The hierarchy list displays all of the hierarchy definitions in a particular topic map. This list can be found on...",""],
["hierarchy_navigator.htm","Hierarchy Navigator","Hierarchy Navigator Top Previous Next The Hierarchy Navigator page allows you to browse through a hierarchy. The bread-crumb list (1) shows the pa...",""],
["hierarchy_node.htm","Hierarchy Node","Hierarchy Node Top Previous Next Path /topicmaps/{tm}/hierarchies/{hierarchyId}/{topicId} Description A node in a topic map hierarchy. The {topicI...",""],
["hierarchy_node_children.htm","Hierarchy Node Children","Hierarchy Node Children Top Previous Next Path /topicmaps/{tm}/topics/{hierarchyId}/{topicId}/children Description The collection of child nodes o...",""],
["hierarchy_node_parents.htm","Hierarchy Node Parents","Hierarchy Node Parents Top Previous Next Path /topicmaps/{tm}/topics/{hierarchyId}/{topicId}/parents Description The collection of parent nodes of...",""],
["how_to.htm","How-To","How-To Top ",""],
["identifierref.htm","IdentifierRef","IdentifierRef Top Previous Next Description Representation of a single identifier resource XML Representation %identifier URI% JSON Representation...",""],
["identifiers_editor.htm","Identifiers Editor","Identifiers Editor Top Previous Next Any type created in the schema may have multiple subject identifiers - this can often be useful for combining...",""],
["identifiers_editor2.htm","Identifiers Editor","Identifiers Editor Top Previous Next The Identifiers Editor provides a simple interface for managing a list of URI identifiers. The screenshot bel...",""],
["iis.htm","IIS","IIS Top Previous Next The Web3 Platform server runs on IIS. IIS 7.0 or later is required. The following features must be enabled in the IIS instal...",""],
["iis_2.htm","IIS_2","IIS Top Previous Next The Web3 Platform server runs on IIS. IIS 7.0 or later is required. The following features must be enabled in the IIS instal...",""],
["iis_3.htm","IIS_3","IIS Top Previous Next The Web3 Platform server runs on IIS. IIS 7.0 or later is required. The following features must be enabled in the IIS instal...",""],
["iis_configuration.htm","IIS Configuration","IIS Configuration Top Previous Next This section covers topics relating to the configuration of the IIS instance that hosts Web3 services. ",""],
["import_topicmap.htm","Import-TopicMap","Import-TopicMap Top Previous Next Summary Import-TopicMap [-TopicMapAddress] [-FilePath] [-BaseUri] [-Follow] [-DefaultLanguage] Description Impor...",""],
["installation.htm","Installation","Installation Top Previous Next This section takes you through aspects of deployment planing to determine which components of the Web3 Platform are...",""],
["installation_process.htm","Installation Process","Installation Process Top Previous Next Getting Started The standard Web3 platform installation is provided in two separate ZIP files, one for 32-b...",""],
["installation_process2.htm","Installation Process","Installation Process Top Previous Next Getting Started The standard Web3 platform installation is provided in two separate ZIP files, one for 32-b...",""],
["installation_process3.htm","Installation Process","Installation Process Top Previous Next Getting Started The standard Web3 platform installation is provided in two separate ZIP files, one for 32-b...",""],
["installation_process4.htm","Installation Process","Installation Process Top Previous Next Getting Started The standard Web3 platform installation is provided in two separate ZIP files, one for 32-b...",""],
["installing_the_snap_in.htm","Installing The Snap-In","Installing The Cmdlets Top Previous Next The Powershell cmdlets are provided by a PowerShell snap-in called \"Web3Admin\". This snap-in is provided ...",""],
["introduction.htm","Introduction","Introduction Top Next Thank you for installing the Web3 Platform from NetworkedPlanet. This document provides useful information for administrator...",""],
["job.htm","Job","Job Top Previous Next Path /topicmaps/{tm}/jobs/{job} Description A batch processing job that executes against a specific topic map Supported HTTP...",""],
["jobdatareference.htm","JobDataReference","JobDataReference Top Previous Next Description Represents a reference to a single binary job data parameter. XML Representation JSON Representatio...",""],
["jobprogressrepr.htm","JobProgressRepr","JobProgressRepr Top Previous Next Description Represents the progress of a long-running job. This structure is found as a child of the JobStatusRe...",""],
["jobrepr.htm","JobRepr","JobRepr Top Previous Next Description Representation of a Job without status information. Used to create an update jobs. XML Representation %job p...",""],
["jobservice.htm","jobService","jobService Top Previous Next This element wraps the configuration options for the Web3 Platform Job Processing Service. It contains the following ...",""],
["jobstatusrepr.htm","JobStatusRepr","JobStatusRepr Top Previous Next Description Representation of a long-running job that includes the current job status information. XML Representat...",""],
["jobs_collection.htm","Jobs Collection","Jobs Collection Top Previous Next Path /topicmaps/{tm}/jobs Description The collection of batch processing jobs that have been queued for the topi...",""],
["job_data.htm","Job Data","Job Data Top Previous Next Path /topicmaps/{tm}/jobs/{job}/{key} Description Binary data associated with a job. Job data can be input data, output...",""],
["job_details_page.htm","Job Details Page","Job Details Page Top Previous Next The Job Details page provides information about a specific job. The Data section contains links to the original...",""],
["jsonp.htm","JSONP","JSONP Top Previous Next The Web3 server supports JSONP callbacks. To have JSON content returned using JSONP, specify the name of the JSONP callbac...",""],
["labelrepr.htm","LabelRepr","LabelRepr Top Previous Next Description Represents a text label in a specific language. XML Representation %label string value% JSON Representatio...",""],
["labels.htm","Labels","Labels Top Previous Next Labels are an extension to the topic maps names mechanism that makes it much easier for topic map creators and consumers ...",""],
["label_editor.htm","Label Editor","Label Editor Top Previous Next Label editors allow you to enter the labels for a topic in multiple languages. Each language is represented with a ...",""],
["licensing.htm","Licensing","Licensing Top Previous Next The Web3 Platform uses a simple license activation scheme to ensure that all server installations are correctly licens...",""],
["limitations.htm","Limitations","Limitations Top Previous Next The Web3 Platform implementation of SPARQL imposes a few restrictions on the general SPARQL query language. 1. Suppo...",""],
["linkeddataserverconfig_xml.htm","linkedDataServerConfig.xml","linkedDataServerConfig.xml Top Previous Next This configuration file contains configuration for exposing Linked Data functionality from a web3 ser...",""],
["linked_data.htm","Linked Data","Linked Data Top Previous Next Although the concept has many different definitions, most of them agree that Linked Data is an way to publish struct...",""],
["listrepr.htm","ListRepr","ListRepr Top Previous Next Description There are a number of different implementation classes that all inherit from the base class NetworkedPlanet...",""],
["loading_the_snap_in.htm","Loading The Snap-In","Loading The Snap-In Top Previous Next To check if the snap-in is currently installed use the following PowerShell command: Get-PSSnapin -Registere...",""],
["locking_down_web3.htm","Locking Down Web3","Locking Down Web3 Top Previous Next When the Web3 Platform is first installed, the security database is pre-configured with an entry that grants f...",""],
["logging.htm","logging","logging Top Previous Next This is the wrapper element for configurations regarding the logging performed by the Web3 Platform web application and ...",""],
["managing_long_running_jobs.htm","Managing Long Running Jobs","Managing Long Running Jobs Top Previous Next As well as transactions there are other long running jobs that are suited to asynchronous processing....",""],
["managing_security.htm","Managing Security","Managing Security Top Previous Next In this section: Security Concepts - provides information about the key concepts in Web3 Platform security. Se...",""],
["manually_adding_a_web3_website.htm","Manually Adding a Web3 Website to IIS","Manually Adding a Web3 Website to IIS Top Previous Next The Web3 Platform installer offers to automatically install the web application at /web3 u...",""],
["mergedconstraintrepr.htm","MergedConstraintRepr","MergedConstraintRepr Top Previous Next Description XML Representation %si% %si% %si% %si% %si% %si% %association type si% %si% %si% %si% 0 1 %regu...",""],
["mergedschemarepr.htm","MergedSchemaRepr","MergedSchemaRepr Top Previous Next Description Represents the results of merging two or more schemas XML Representation See SchemaSummaryRepr * Se...",""],
["mergedtyperepr.htm","MergedTypeRepr","MergedTypeRepr Top Previous Next Description Represents a schema type in a merged schema. The type may be the result of merging two or more source...",""],
["merging_topics.htm","Merging Topics","Merging Topics Top Previous Next The TopicMap class provides a method to merge two topics (TopicMap.MergeTopics(Uri, Uri)). The topics to be merge...",""],
["microsoft_message_queue.htm","Microsoft Message Queue","Microsoft Message Queue Top Previous Next The following MSMQ features must be enabled on all machines that host Web3 services. Microsoft Message Q...",""],
["microsoft_message_queue_2.htm","Microsoft Message Queue_2","Microsoft Message Queue Top Previous Next The following MSMQ features must be enabled on all machines that host Web3 services. Microsoft Message Q...",""],
["microsoft_message_queue_3.htm","Microsoft Message Queue_3","Microsoft Message Queue Top Previous Next The following MSMQ features must be enabled on all machines that host Web3 services. Microsoft Message Q...",""],
["multiple_front_end_deployment.htm","Multiple Front-End Deployment","Multiple Front-End Deployment Top Previous Next Multiple Front End Servers In this configuration, further scaling is achieved by providing multipl...",""],
["multi_value_editor.htm","Multi-Value Editor","Multi-Value Editor Top Previous Next The Multi-Value Editor is a wrapper around one of the other types of editor that allows you to have multiple ...",""],
["navigating_a_hierarchy.htm","Navigating A Hierarchy","Navigating A Hierarchy Top Previous Next To navigate a hierarchy, first select the hierarchy from the Hierarchies tab in the left-hand panel of th...",""],
["navigation_and_selection.htm","Navigation and Selection","Navigation and Selection Top Previous Next Schema with the \"Term\" Topic Type Selected Selecting Types To select a type simply click on its shape i...",""],
["new_pool.htm","New-Pool","New-Pool Top Previous Next Summary New-Pool [-TopicMapAddress] [-Name] [-DenyTypes ] New-Pool [-TopicMapAddress] [-Name] -AllowTypes Description C...",""],
["new_schema.htm","New-Schema","New-Schema Top Previous Next Summary New-Schema [-Web3Address] [-FilePath] Description Creates a new schema in the specified service using the XML...",""],
["new_topicmap.htm","New-TopicMap","New-TopicMap Top Previous Next Summary New-TopicMap [-ServiceUrl] [-Schema] [-Labels ] [-WebLabel ] Description Creates a new topic map in the top...",""],
["occurrences.htm","Names and Occurrences","Names and Occurrences Top Previous Next Names and occurrences are constructs that add properties to topics. Names are properties that are intended...",""],
["paging_list_results.htm","Paging List Results","Paging List Results Top Previous Next All results that return a list of objects support paging through the use of two optional parameters: skip: s...",""],
["password.htm","password","password Top Previous Next The content of this element is the password for the Active Directory Role Provider to use when accessing Active Directo...",""],
["permissionrepr.htm","PermissionRepr","PermissionRepr Top Previous Next Description Represents a permission or set of permissions assigned to a user XML Representation JSON Representati...",""],
["platform_configuration.htm","Platform Configuration","Platform Configuration Top Previous Next This section provides information about how to configure different aspects of the Web3 Platform services. ",""],
["polling.htm","polling","polling Top Previous Next This element specifies how long the Web3 Job Processing Service waits in between checks of the Job Store for new jobs to...",""],
["poolref.htm","PoolRef","PoolRef Top Previous Next Description Represents a reference to a topic map pool. XML Representation %pool name% JSON Representation { \"Address\":\"...",""],
["poolrepr.htm","PoolRepr","PoolRepr Top Previous Next Description Represents the configuration of a single topic map pool XML Representation %pool name % true %type si% %typ...",""],
["populating_a_topic_map_with_da.htm","Populating a Topic Map With Data","Populating a Topic Map With Data Top Previous Next The main use for the client is to create topic map data, e.g. topics, topic properties and asso...",""],
["powershell_cmdlets.htm","Powershell Cmdlets","Powershell Cmdlets Top Previous Next This section describes the PowerShell Cmdlets that are added by the Web3Admin Powershell snap-in. Installing ...",""],
["predefined_extension_propertie.htm","Predefined Extension Properties","Predefined Extension Properties Top Previous Next NetworkedPlanet have defined a number of schema type extension properties that are recognized by...",""],
["prepare_for_installation.htm","Prepare for installation","Prepare for installation Top Previous Next Before installing the software please ensure that: 1. All pre-requisite software and features have been...",""],
["prepare_for_installation2.htm","Prepare for installation","Prepare for installation Top Previous Next Before installing the software please ensure that: 1. All pre-requisite software and features have been...",""],
["prepare_for_installation3.htm","Prepare for installation","Prepare for installation Top Previous Next Before installing the software please ensure that: 1. All pre-requisite software and features have been...",""],
["prepare_for_installation4.htm","Prepare for installation","Prepare for installation Top Previous Next Before installing the software please ensure that: 1. All pre-requisite software and features have been...",""],
["pre_requisites.htm","Pre-requisites","Pre-requisites Top Previous Next The following required software must be installed on the machine prior to attempting to install the Web3 Platform. ",""],
["pre_requisites2.htm","Pre-requisites","Pre-requisites Top Previous Next The following required software must be installed on the machine prior to attempting to install the Web3 Platform...",""],
["pre_requisites3.htm","Pre-requisites","Pre-requisites Top Previous Next The following required software must be installed on the machine prior to attempting to install the Web3 Platform...",""],
["pre_requisites4.htm","Pre-requisites","Pre-requisites Top Previous Next The following required software must be installed on the machine prior to attempting to install the Web3 Platform...",""],
["property_editors.htm","Property Editors","Property Editors Top Previous Next The topic editor supports several different kinds of property editor. Which one is used depends on the Data Typ...",""],
["querying.htm","Querying","Querying Top Previous Next The Web3 platform provides support for two different types of query, full text query and structured query using the SPA...",""],
["querying_a_topic_map_using_spa.htm","Querying a Topic Map using SPARQL","Querying a Topic Map using SPARQL Top Previous Next This is not a full guide to writing SPARQL but shows how to invoke SPARQL queries from the .NE...",""],
["querying_with_sparql.htm","Querying with SPARQL","Querying with SPARQL Top Previous Next The Web3 platform supports the SPARQL query language as a way to search the Topic Map. SPARQL is a standard...",""],
["queryresultsrepr.htm","QueryResultsRepr","QueryResultsRepr Top Previous Next Description Represents a page of results in a paged query results set. XML Representation * JSON Representation...",""],
["query_topicmap.htm","Query-TopicMap","Query-TopicMap Top Previous Next Summary Query-TopicMap [-TopicMapAddress] [-Query] Description Runs a SPARQL query against a topic map and displa...",""],
["referring_to_topics_and_schema.htm","Referring to Topics and Schema Types","Referring to Topics and Schema Types Top Previous Next SPARQL queries are built from a number of triple patterns. Each triple pattern defines a su...",""],
["removing_types_and_constraints.htm","Removing Types and Constraints","Removing Types and Constraints Top Previous Next Types can be removed from the schema in one of two ways, depending on what kind of Type it is. To...",""],
["representations.htm","Representations","Representations Top Previous Next To use the web services directly is is necessary to know the representations that can be sent to and from the se...",""],
["requesting_a_specific_format.htm","Requesting a Specific Format","Requesting a Specific Format Top Previous Next All Web3 resources support multiple representation formats. The Web3 services support two ways of r...",""],
["responserepr.htm","ResponseRepr","ResponseRepr Top Previous Next Description Represents the results of processing a single ActionRepr in a TransactionRepr . XML Representation %res...",""],
["rest_api_reference.htm","REST API Reference","REST API Reference Top ",""],
["rest_interface_reference.htm","REST Interface Reference","REST Interface Reference Top Previous Next This section describes the REST interface provided by the Web3 Platform. ",""],
["rest_vs__net_apis.htm","REST vs .NET APIs","REST vs .NET APIs Top Previous Next All the services in the Web3 Platform are RESTful web services. There are no client APIs that connect directly...",""],
["rich_text_editor.htm","Rich Text Editor","Rich Text Editor Top Previous Next The Rich Text Editor is displayed only for properties that have been configured with a special extension proper...",""],
["roleprovider.htm","roleProvider","roleProvider Top Previous Next The roleProvider element specifies the implementation that will be used to return a list of user roles for a given ...",""],
["rolerepr.htm","RoleRepr","RoleRepr Top Previous Next Description Representation of a single role within an association. XML Representation See TopicRef See TopicRef JSON Re...",""],
["rootpath.htm","rootPath","rootPath Top Previous Next This element contains the ActiveDirectory Root Container Path to be searched when looking for users and the groups they...",""],
["schema.htm","Schema","Schema Top Previous Next Path /schemas/{schema} Description A single schema Supported HTTP Operations HTTP Method Description Supported Formats GE...",""],
["schemarepr.htm","SchemaRepr","SchemaRepr Top Previous Next Description Representation of a topic map schema. XML Representation %schema si% %schema base si% %schema label% See ...",""],
["schemaservice.htm","schemaService","schemaService Top Previous Next This element wraps the configuration options for the Web3 Platform Schema Store. It contains the following child e...",""],
["schemastore.htm","schemaStore","schemaStore Top Previous Next This element is a wrapper for the configuration elements that apply to the Web3 Platform Schema store. This element ...",""],
["schemasummaryrepr.htm","SchemaSummaryRepr","SchemaSummaryRepr Top Previous Next Description Provides summary metadata about a schema. XML Representation %schema label% %schema si% %schema ba...",""],
["schema_collection.htm","Schema Collection","Schema Collection Top Previous Next Path /schemas/ Description The collection of schemas managed by the Web3 service. Supported HTTP Operations HT...",""],
["schema_editor.htm","Schema Editor","Schema Editor Top Previous Next The schema editor provides a graphical tool for creating and updating topic map schemas. It is opened from the Web...",""],
["schema_home_page.htm","Schema Home Page","Schema Home Page Top Previous Next The Schema Home Page is the root page for a specific schema. This page can be directly linked to at http://{ser...",""],
["schema_meta_data.htm","Schema Meta Data","Schema Meta Data Top Previous Next Every schema has some optional meta data properties which are made available through the schema editor applicat...",""],
["schema_permissions.htm","Schema Permissions","Schema Permissions Top Previous Next Path /schemas/{schema}/permissions Description The permissions granted on a schema. Supported HTTP Operations...",""],
["schema_service_resources.htm","Schema Service Resources","Schema Service Resources Top Previous Next This section lists all of the resources provided by the Web3 Schema Service. ",""],
["schema_store_permissions.htm","Schema Store Permissions","Schema Store Permissions Top Previous Next Path /schemas/permissions Description Represents the collection of permissions granted on the Web3 topi...",""],
["schema_summary.htm","Schema Summary","Schema Summary Top Previous Next Path /schemas/{schema}/summary Description Schema meta-data resource Supported HTTP Operations HTTP Method Descri...",""],
["schema_synchronization.htm","Schema Synchronization","Schema Synchronization Top Previous Next The Web3 Platform maintains schemas and topic maps as totally separate items. When you create a new topic...",""],
["schema_type.htm","Schema Type","Schema Type Top Previous Next Path /schemas/{schema}/types/{type} Description A single type in a schema. Supported HTTP Operations HTTP Method Des...",""],
["schema_types.htm","Schema Types","Schema Types Top Previous Next Each type in a schema defines the following properties: The identifier(s) for the schema type. Every schema type mu...",""],
["schema_types_collection.htm","Schema Types Collection","Schema Types Collection Top Previous Next Path /schemas/{schema}/types Description The collection of types defined by a schema. Supported HTTP Ope...",""],
["scope.htm","Scope","Scope Top Previous Next Scope is the term used in the topic map standard to refer to a constraint or a context in which something is said about a ...",""],
["securitymanager.htm","securityManager","securityManager Top Previous Next This element is the wrapper for configuration elements that configure aspects of access control and security man...",""],
["security_concepts.htm","Security Concepts","Security Concepts Top Previous Next This section covers the basic concepts require to understand how the Web3 Platform implements access controls ...",""],
["security_operations.htm","Security Operations","Security Operations Top Previous Next This section provides how-to guides for some basic Web3 Platform security procedures: Locking Down Web3 Gran...",""],
["select_topicmap.htm","Select-TopicMap","Select-TopicMap Top Previous Next Summary Select-TopicMap [-ServiceUrl] [-TopicMapAddress ] [-Labels ] Description Returns a list of topic maps in...",""],
["server.htm","server","server Top Previous Next This is the root element of the server configuration file. It contains the following child elements, each occurring at mo...",""],
["serverconfig_xml.htm","serverConfig.xml","serverConfig.xml Top Previous Next This configuration file is the main configuration file for all Web3 Platform services, controlling aspects such...",""],
["server_logs.htm","Server Logs","Server Logs Top Previous Next If an error occurs and it is unclear from the exception what the problem is then it is recommended to consult the lo...",""],
["setup.htm","Setup","Setup Top Previous Next To start developing using the API install the web3 platform and reference the following DLLs. Note: If you are developing ...",""],
["set_topicmap.htm","Set-TopicMap","Set-TopicMap Top Previous Next Summary Set-TopicMap [-TopicMapAddress] [-Schema ] [-Labels ] [-WebLabel ] -RemoveOldLabels Description Updates the...",""],
["simple_validating_text_editor.htm","Simple Validating Text Editor","Simple Validating Text Editor Top Previous Next A validating text editor displays simply as a text box into which you type the value. When you cli...",""],
["single_front_end_deployment.htm","Single Front-End Deployment","Single Front-End Deployment Top Previous Next Single Front End Server This configuration places the Web3 databases on a remote database server. Th...",""],
["single_server_deployemnt.htm","Single-Server Deployment","Single-Server Deployment Top Previous Next Single Server Deployment This is the simplest configuration. It is the only configuration supported by ...",""],
["sql_server_with_full_text_inde.htm","SQL Server with Full Text Indexing","SQL Server with Full Text Indexing Top Previous Next The Web3 Platform depends on SQL Server for back-end data persistence. SQL Server must be ins...",""],
["sql_server_with_full_text_inde_2.htm","SQL Server with Full Text Indexing","SQL Server with Full Text Indexing Top Previous Next The Web3 Platform depends on SQL Server for back-end data persistence. SQL Server must be ins...",""],
["storeid.htm","storeId","storeId Top Previous Next The storeId element specifies a unique name for a topic map or schema store. This name is used as a key for the store&#39;s ...",""],
["stores_and_pools.htm","Stores and Partitions","Stores and Partitions Top Previous Next In the Web3 Platform, user permissions are granted on containers of data. A Store is the highest level dat...",""],
["success_status_codes.htm","Success Status Codes","Success Status Codes Top Previous Next In conformance with HTTP standards, the Web3 server will return a 200 OK on a successful GET or PUT. A succ...",""],
["sync_topicmap.htm","Sync-TopicMap","Sync-TopicMap Top Previous Next Summary Sync-TopicMap [-TopicMapAddress] [-Follow] Description Synchronizes a topic map with the schema it referen...",""],
["tab_bar.htm","Tab Bar","Tab Bar Top Previous Next The Tab Bar provides an interface for editing the more advanced aspects of a topic which most editors will generally not...",""],
["take.htm","take","take Top Previous Next This element controls the default and maximum page sizes returned by list operations. It has two attributes: default: speci...",""],
["textsearchhitrepr.htm","TextSearchHitRepr","TextSearchHitRepr Top Previous Next Description Represents a single result in a full-text search results set. XML Representation %double% See Topi...",""],
["textsearchquery.htm","TextSearchQuery","TextSearchQuery Top Previous Next Description Representation of a full-text search query. XML Representation %PropertiesOnly|LabelsOnly|LabelsAndP...",""],
["tmsparql_created_predicate.htm","TMSparql Created Predicate","TMSparql Created Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_datetime_value_predic.htm","TMSparql DateTime Value Predicate","TMSparql DateTime Value Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_decimal_value_predica.htm","TMSparql Decimal Value Predicate","TMSparql Decimal Value Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_double_value_predicat.htm","TMSparql Double Value Predicate","TMSparql Double Value Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_integer_value_predica.htm","TMSparql Integer Value Predicate","TMSparql Integer Value Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_item_identifier_predi.htm","TMSparql Item Identifier Predicate","TMSparql Item Identifier Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_label_predicate.htm","TMSparql Label Predicate","TMSparql Label Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_modified_predicate.htm","TMSparql Modified Predicate","TMSparql Modified Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_player_predicate.htm","TMSparql Player Predicate","TMSparql Player Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_reifier_predicate.htm","TMSparql Reifier Predicate","TMSparql Reifier Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_role_predicate.htm","TMSparql Role Predicate","TMSparql Role Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_scope_predicate.htm","TMSparql Scope Predicate","TMSparql Scope Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_subject_identifier_pr.htm","TMSparql Subject Identifier Predicate","TMSparql Subject Identifier Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_subject_locator_predi.htm","TMSparql Subject Locator Predicate","TMSparql Subject Locator Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_topic_property_predic.htm","TMSparql Topic Property Predicate","TMSparql Topic Property Predicate Top Previous Next This is a placeholder for future content. ",""],
["tmsparql_value_predicate.htm","TMSparql Value Predicate","TMSparql Value Predicate Top Previous Next This is a placeholder for future content. ",""],
["topic.htm","Topic","Topic Top Previous Next Path /topicmaps/{tm}/topics/{topic} Description A single topic in a topic map Supported HTTP Operations HTTP Method Descri...",""],
["topicmaprepr.htm","TopicMapRepr","TopicMapRepr Top Previous Next Description Representation of key topic map meta-data. XML Representation See LabelRepr * JSON Representation { \"Ad...",""],
["topicmapschemarepr.htm","TopicMapSchemaRepr","TopicMapSchemaRepr Top Previous Next Description Representation of the schema attached to a topic map. XML Representation See SchemaSummaryRepr * ...",""],
["topicmapservice.htm","topicMapService","topicMapService Top Previous Next This element is a wrapper around the configuration elements that apply to the Web3 Platform&#39;s topic map web serv...",""],
["topicmapstore.htm","topicMapStore","topicMapStore Top Previous Next This element wraps the configuration options for the Web3 Platform Topic Map Store. It contains the following chil...",""],
["topicpropertyrepr.htm","TopicPropertyRepr","TopicPropertyRepr Top Previous Next Description Representation of a topic property (a topic name or occurrence). XML Representation See TopicRef %...",""],
["topicref.htm","TopicRef","TopicRef Top Previous Next Description Represents a reference to a topic. Note that topic type references show only the web address of the typing ...",""],
["topicrepr.htm","TopicRepr","TopicRepr Top Previous Next Description Representation of a topic including all of its properties (names and occurrences), identifiers and labels....",""],
["topics.htm","Topics","Topics Top Previous Next A topic is a machine-processable representation of a concept. The Topic Maps standard does not restrict the set of concep...",""],
["topic_arcs_collection.htm","Topic Arcs Collection","Topic Arcs Collection Top Previous Next Path /topicmaps/{tm}/topics/{topic}/associations Description The collection of arcs in which the topic par...",""],
["topic_associations_collection.htm","Topic Associations Collection","Topic Associations Collection Top Previous Next Path /topicmaps/{tm}/topics/{topic}/associations Description The collection of associations in whi...",""],
["topic_editor.htm","Topic Editor","Topic Editor Top Previous Next The Web3 Platform provides an editor that can be used for modifying existing topics. The editor can be found by cli...",""],
["topic_identifier.htm","Topic Identifier","Topic Identifier Top Previous Next Path /topicmaps/{tm}/topics/{topic}/identifiers/{id} Description Represents a single topic identifier Supported...",""],
["topic_identifiers_collection.htm","Topic Identifiers Collection","Topic Identifiers Collection Top Previous Next Path /topicmaps/{tm}/topics/{topic}/identifiers Description The collection of identifiers assigned ...",""],
["topic_map.htm","Topic Map","Topic Map Top Previous Next Path /topicmaps/{tm} Description A single topic map managed by the Web3 Platform Supported HTTP Operations HTTP Method...",""],
["topic_maps.htm","Topic Maps","Topic Maps Top Previous Next Topic Maps is a standard (ISO 13250) that defines a model and a syntax for the representation of knowledge. The stand...",""],
["topic_maps_and_rdf.htm","Topic Maps and RDF","Topic Maps and RDF Top Previous Next Although Web3 has an internal model based on the Topic Maps standard, the application is capable of presentin...",""],
["topic_map_batch_processor.htm","Topic Map Batch Processor","Topic Map Batch Processor Top Previous Next Path /topicmaps/{tm}/batch Description The topic map batch processor. Supported HTTP Operations HTTP M...",""],
["topic_map_browser.htm","Topic Map List Page","Topic Map List Page Top Previous Next The topic map service provides not only a way to fetch topic map data in XML or JSON it also delivers HTML s...",""],
["topic_map_editor_page.htm","Topic Map Editor","Topic Map Editor Top Previous Next The topic map editor is a complete browser-based interface for managing the topics and hierarchies in a topic m...",""],
["topic_map_hierarchies_collecti.htm","Topic Map Hierarchies Collection","Topic Map Hierarchies Collection Top Previous Next Path /topicmaps/{tm}/hierarchies Description The collection of hierarchy definitions contained ...",""],
["topic_map_home_page.htm","Topic Map Home Page","Topic Map Home Page Top Previous Next The Topic Map Home Page is the root page for a specific topic map. This page can be directly linked to at ht...",""],
["topic_map_jobs_page.htm","Topic Map Jobs Page","Topic Map Jobs Page Top Previous Next The Topic Map Jobs Page lists all the jobs that have executed, or been scheduled for execution along with th...",""],
["topic_map_permissions.htm","Topic Map Permissions","Topic Map Permissions Top Previous Next Path /topicmaps/{tm}/permissions Description The permissions granted on a topic map Supported HTTP Operati...",""],
["topic_map_pool.htm","Topic Map Pool","Topic Map Pool Top Previous Next Path /topicmaps/{tm}/pools/{pool} Description The configuration of a single pool in the topic map. Supported HTTP...",""],
["topic_map_pool_collection.htm","Topic Map Pool Collection","Topic Map Pool Collection Top Previous Next Path /topicmaps/{tm}/pools Description The collection of pools within a topic map Supported HTTP Opera...",""],
["topic_map_pool_permissions.htm","Topic Map Pool Permissions","Topic Map Pool Permissions Top Previous Next Path /topicmaps/{tm}/pools/{pool}/permissions Description Topic map pool permissions collection. Supp...",""],
["topic_map_reifier.htm","Topic Map Reifier","Topic Map Reifier Top Previous Next Path /topicmaps/{tm}/reifier Description Redirects to the topic that reifies the topic map Supported HTTP Oper...",""],
["topic_map_schema.htm","Topic Map Schema","Topic Map Schema Top Previous Next Path /topicmaps/{tm}/types Description The topic map schema resource. Supported HTTP Operations HTTP Method Des...",""],
["topic_map_schemas.htm","Topic Map Schemas","Topic Map Schemas Top Previous Next Although not required to use the Web3 API, a topic map schema allows you to make use of the schema-driven brow...",""],
["topic_map_search_page.htm","Topic Map Search Page","Topic Map Search Page Top Previous Next The Topic Map Search Page is used to search through the topics in a topic map by their names or label valu...",""],
["topic_map_service_resources.htm","Topic Map Service Resources","Topic Map Service Resources Top Previous Next This section lists all of the resources provided by the Topic Map Service REST interface. ",""],
["topic_map_store.htm","Topic Map Store","Topic Map Store Top Previous Next Path /topicmaps/ Description The resource that represents the collection of topic maps managed by the Web3 servi...",""],
["topic_map_store_permissions.htm","Topic Map Store Permissions","Topic Map Store Permissions Top Previous Next Path /topicmaps/permissions Description Represents the collection of permissions granted on the Web3...",""],
["topic_map_topics_collection.htm","Topics Collection","Topics Collection Top Previous Next Path /topicmaps/{tm}/topics Description The collection of topics in the topic map. Supported HTTP Operations H...",""],
["topic_merging.htm","Topic Merging","Topic Merging Top Previous Next Automatic topic merging is a key feature of topic maps and one that brings many benefits to topic map development ...",""],
["topic_page.htm","Topic Page","Topic Page Top Previous Next The Topic Page displays key information about a single topic in the topic map. The page can be directly linked to at ...",""],
["topic_properties_collection.htm","Topic Properties Collection","Topic Properties Collection Top Previous Next Path /topicmaps/{tm}/topics/{topic}/properties Description The collection of properties (names and o...",""],
["topic_property.htm","Topic Property","Topic Property Top Previous Next Path /topicmaps/{tm}/topics/{topic}/properties/{prop} Description A single topic property Supported HTTP Operatio...",""],
["topic_types.htm","Topic Types","Topic Types Top Previous Next The Topic Types tab in the left-hand panel allows you to browse the topic map by topic type and to create new topics...",""],
["topic_types_list.htm","Topic Types List","Topic Types List Top Previous Next The Topic Types List displays the schema types that are allowed for new topics created in the topic map. This l...",""],
["topic_type_page.htm","Topic Type Page","Topic Type Page Top Previous Next The Topic Type Page displays information about all topics of a particular type. Topic Type Page The Topic Type P...",""],
["transactionrepr.htm","TransactionRepr","TransactionRepr Top Previous Next Description Representation of a collection of topic map update actions to be performed as a single transaction. ...",""],
["transactions.htm","Transactions","Transactions Top Previous Next The nature of the RESTful API is that resource representations are fetched updated and then sent back to the server...",""],
["traversing_associations.htm","Traversing Associations and Arcs","Finding Related Topics Top Previous Next The simplest way to find all topics related to another topic is to use a single predicate where the subje...",""],
["traversing_topic_map_structure.htm","Traversing Topic Map Structures","Traversing Topic Map Structures Top Previous Next The Web3 Platform implementation of SPARQL provides a number of \"built-in\" predicates that allow...",""],
["troubleshooting.htm","Troubleshooting","Troubleshooting Top Previous Next This section describes some issues that may arise when installing the Web3 Platform and ways to address them. We...",""],
["typepropertyrepr.htm","TypePropertyRepr","TypePropertyRepr Top Previous Next Description Representation of an extension property assigned to a schema type. XML Representation %type propert...",""],
["typerefrepr.htm","TypeRefRepr","TypeRefRepr Top Previous Next Description Representation of a reference to a schema type. XML Representation See LabelRepr * JSON Representation {...",""],
["typerepr.htm","TypeRepr","TypeRepr Top Previous Next Description Representation of a type in a schema. XML Representation %boolean% %boolean% %boolean% %boolean% %boolean% ...",""],
["types_editor.htm","Types Editor","Types Editor Top Previous Next The Types Editor interface is a simple two-list selector as shown in the screenshot below. Tab Bar with Types Edito...",""],
["upgrading_from_previous_versio.htm","Upgrading From Previous Versions","Upgrading From Previous Versions Top Previous Next To upgrade from a previous version of the Web3 platform, simply run the installer as normal, fo...",""],
["username.htm","userName","userName Top Previous Next This element specifies the name of the user account to use when accessing Active Directory to lookup users and their gr...",""],
["user_guides.htm","User Guides","User Guides Top Previous Next ",""],
["web3_extensions.htm","Web3 Extensions","Web3 Extensions Top Previous Next As well as implementing the basic Topic Maps model Web3 provides a couple of useful extensions to the model. The...",""],
["web3_hive_directory.htm","Web3 Hive Directory","Web3 Hive Directory Top Previous Next All configuration and logging files for a Web3 Platform installation are contained in the Web3 Hive Director...",""],
["web3_home_page.htm","Web3 Home Page","Web3 Home Page Top Previous Next The Web3 home page is located at http://{server}/web3/ and shows a list of the current topic maps and a list of t...",""],
["web3_services.htm","Web3 Services","Web3 Services Top Previous Next Before looking at the different APIs here is a short overview of the different services exposed by the Web3 Platfo...",""],
["windows_communication_foundati.htm","Windows Communication Foundation","Windows Communication Foundation Top Previous Next The following WCF features must be enabled on all machines that host Web3 services. Windows Com...",""],
["windows_communication_foundati_2.htm","Windows Communication Foundation_2","Windows Communication Foundation Top Previous Next The following WCF features must be enabled on all machines that host Web3 services. Windows Com...",""],
["windows_communication_foundati_3.htm","Windows Communication Foundation_3","Windows Communication Foundation Top Previous Next The following WCF features must be enabled on all machines that host Web3 services. Windows Com...",""],
["workerthreads.htm","workerThreads","workerThreads Top Previous Next This element allows the configuration of the number of worker threads that the Web3 Job Processing Service uses. H...",""]];
